using System.Text.Json;
using Pgan.PoracleWebNet.Core.Models;
using Pgan.PoracleWebNet.Data.Entities;

namespace Pgan.PoracleWebNet.Core.Mappings;

public static class EntityMappingExtensions
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
    };

    // ── Human ────────────────────────────────────────────────

    public static Human ToModel(this HumanEntity e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        Type = e.Type,
        Enabled = e.Enabled,
        Area = e.Area,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
        Fails = e.Fails,
        Language = e.Language,
        AdminDisable = e.AdminDisable,
        LastChecked = e.LastChecked,
        DisabledDate = e.DisabledDate,
        CurrentProfileNo = e.CurrentProfileNo,
        CommunityMembership = e.CommunityMembership,
        Notes = e.Notes,
    };

    public static HumanEntity ToEntity(this Human m) => new()
    {
        Id = m.Id,
        Name = m.Name ?? string.Empty,
        Type = m.Type ?? string.Empty,
        Enabled = m.Enabled,
        Area = m.Area ?? string.Empty,
        Latitude = m.Latitude,
        Longitude = m.Longitude,
        Fails = m.Fails,
        Language = m.Language,
        AdminDisable = m.AdminDisable,
        LastChecked = m.LastChecked,
        DisabledDate = m.DisabledDate,
        CurrentProfileNo = m.CurrentProfileNo,
        CommunityMembership = m.CommunityMembership ?? string.Empty,
        Notes = m.Notes ?? string.Empty,
    };

    public static void ApplyTo(this Human src, HumanEntity dest)
    {
        dest.Name = src.Name ?? string.Empty;
        dest.Type = src.Type ?? string.Empty;
        dest.Enabled = src.Enabled;
        dest.Area = src.Area ?? string.Empty;
        dest.Latitude = src.Latitude;
        dest.Longitude = src.Longitude;
        dest.Fails = src.Fails;
        dest.Language = src.Language;
        dest.AdminDisable = src.AdminDisable;
        dest.LastChecked = src.LastChecked;
        dest.DisabledDate = src.DisabledDate;
        dest.CurrentProfileNo = src.CurrentProfileNo;
        dest.CommunityMembership = src.CommunityMembership ?? string.Empty;
        dest.Notes = src.Notes ?? string.Empty;
    }

    // ── Profile ──────────────────────────────────────────────

    public static Profile ToModel(this ProfileEntity e) => new()
    {
        Id = e.Id,
        ProfileNo = e.ProfileNo,
        Name = e.Name,
        Area = e.Area,
        Latitude = e.Latitude,
        Longitude = e.Longitude,
    };

    public static ProfileEntity ToEntity(this Profile m) => new()
    {
        Id = m.Id,
        ProfileNo = m.ProfileNo,
        Name = m.Name,
        Area = m.Area,
        Latitude = m.Latitude,
        Longitude = m.Longitude,
    };

    public static void ApplyTo(this Profile src, ProfileEntity dest)
    {
        dest.Name = src.Name;
        dest.Area = src.Area;
        dest.Latitude = src.Latitude;
        dest.Longitude = src.Longitude;
    }

    // ── PwebSetting ──────────────────────────────────────────

    public static PwebSetting ToModel(this PwebSettingEntity e) => new()
    {
        Setting = e.Setting,
        Value = e.Value,
    };

    public static PwebSettingEntity ToEntity(this PwebSetting m) => new()
    {
        Setting = m.Setting,
        Value = m.Value,
    };

    public static void ApplyTo(this PwebSetting src, PwebSettingEntity dest)
    {
        dest.Value = src.Value;
    }

    // ── UserGeofence ─────────────────────────────────────────

    public static UserGeofence ToModel(this UserGeofenceEntity e) => new()
    {
        Id = e.Id,
        HumanId = e.HumanId,
        KojiName = e.KojiName,
        DisplayName = e.DisplayName,
        GroupName = e.GroupName,
        ParentId = e.ParentId,
        PolygonJson = e.PolygonJson,
        Status = e.Status,
        SubmittedAt = e.SubmittedAt,
        ReviewedBy = e.ReviewedBy,
        ReviewedAt = e.ReviewedAt,
        ReviewNotes = e.ReviewNotes,
        PromotedName = e.PromotedName,
        DiscordThreadId = e.DiscordThreadId,
        CreatedAt = e.CreatedAt,
        UpdatedAt = e.UpdatedAt,
        // Polygon is intentionally NOT mapped — populated by the service layer from PolygonJson
    };

    public static UserGeofenceEntity ToEntity(this UserGeofence m) => new()
    {
        // Id is intentionally NOT mapped — auto-generated by the database
        HumanId = m.HumanId,
        KojiName = m.KojiName,
        DisplayName = m.DisplayName,
        GroupName = m.GroupName,
        ParentId = m.ParentId,
        PolygonJson = m.PolygonJson,
        Status = m.Status,
        SubmittedAt = m.SubmittedAt,
        ReviewedBy = m.ReviewedBy,
        ReviewedAt = m.ReviewedAt,
        ReviewNotes = m.ReviewNotes,
        PromotedName = m.PromotedName,
        DiscordThreadId = m.DiscordThreadId,
        CreatedAt = m.CreatedAt,
        UpdatedAt = m.UpdatedAt,
    };

    public static void ApplyTo(this UserGeofence src, UserGeofenceEntity dest)
    {
        // Id is intentionally NOT updated — preserve DB identity
        dest.HumanId = src.HumanId;
        dest.KojiName = src.KojiName;
        dest.DisplayName = src.DisplayName;
        dest.GroupName = src.GroupName;
        dest.ParentId = src.ParentId;
        dest.PolygonJson = src.PolygonJson;
        dest.Status = src.Status;
        dest.SubmittedAt = src.SubmittedAt;
        dest.ReviewedBy = src.ReviewedBy;
        dest.ReviewedAt = src.ReviewedAt;
        dest.ReviewNotes = src.ReviewNotes;
        dest.PromotedName = src.PromotedName;
        dest.DiscordThreadId = src.DiscordThreadId;
    }

    // ── SiteSetting ──────────────────────────────────────────

    public static SiteSetting ToModel(this SiteSettingEntity e) => new()
    {
        Id = e.Id,
        Category = e.Category,
        Key = e.Key,
        Value = e.Value,
        ValueType = e.ValueType,
    };

    public static SiteSettingEntity ToEntity(this SiteSetting m) => new()
    {
        Id = m.Id,
        Category = m.Category,
        Key = m.Key,
        Value = m.Value,
        ValueType = m.ValueType,
    };

    // ── WebhookDelegate ──────────────────────────────────────

    public static WebhookDelegate ToModel(this WebhookDelegateEntity e) => new()
    {
        Id = e.Id,
        WebhookId = e.WebhookId,
        UserId = e.UserId,
        CreatedAt = e.CreatedAt,
    };

    public static WebhookDelegateEntity ToEntity(this WebhookDelegate m) => new()
    {
        Id = m.Id,
        WebhookId = m.WebhookId,
        UserId = m.UserId,
        CreatedAt = m.CreatedAt,
    };

    // ── QuickPickDefinition ──────────────────────────────────

    public static QuickPickDefinition ToModel(this QuickPickDefinitionEntity e) => new()
    {
        Id = e.Id,
        Name = e.Name,
        Description = e.Description ?? string.Empty,
        Icon = e.Icon,
        Category = e.Category,
        AlarmType = e.AlarmType,
        SortOrder = e.SortOrder,
        Enabled = e.Enabled,
        Scope = e.Scope,
        OwnerUserId = e.OwnerUserId,
        Filters = string.IsNullOrEmpty(e.FiltersJson)
            ? new Dictionary<string, object?>()
            : JsonSerializer.Deserialize<Dictionary<string, object?>>(e.FiltersJson, JsonOptions)
              ?? new Dictionary<string, object?>(),
    };

    public static QuickPickDefinitionEntity ToEntity(this QuickPickDefinition m) => new()
    {
        Id = m.Id,
        Name = m.Name,
        Description = m.Description,
        Icon = m.Icon,
        Category = m.Category,
        AlarmType = m.AlarmType,
        SortOrder = m.SortOrder,
        Enabled = m.Enabled,
        Scope = m.Scope,
        OwnerUserId = m.OwnerUserId,
        FiltersJson = JsonSerializer.Serialize(m.Filters, JsonOptions),
        CreatedAt = DateTime.UtcNow,
        UpdatedAt = DateTime.UtcNow,
    };

    public static void ApplyTo(this QuickPickDefinition src, QuickPickDefinitionEntity dest)
    {
        dest.Name = src.Name;
        dest.Description = src.Description;
        dest.Icon = src.Icon;
        dest.Category = src.Category;
        dest.AlarmType = src.AlarmType;
        dest.SortOrder = src.SortOrder;
        dest.Enabled = src.Enabled;
        dest.Scope = src.Scope;
        dest.OwnerUserId = src.OwnerUserId;
        dest.FiltersJson = JsonSerializer.Serialize(src.Filters, JsonOptions);
        dest.UpdatedAt = DateTime.UtcNow;
    }

    // ── QuickPickAppliedState ────────────────────────────────

    public static QuickPickAppliedState ToModel(this QuickPickAppliedStateEntity e) => new()
    {
        UserId = e.UserId,
        ProfileNo = e.ProfileNo,
        QuickPickId = e.QuickPickId,
        AlarmType = e.AlarmType,
        AppliedAt = e.AppliedAt,
        ExcludePokemonIds = string.IsNullOrEmpty(e.ExcludePokemonIdsJson)
            ? []
            : JsonSerializer.Deserialize<List<int>>(e.ExcludePokemonIdsJson, JsonOptions) ?? [],
        TrackedUids = string.IsNullOrEmpty(e.TrackedUidsJson)
            ? []
            : JsonSerializer.Deserialize<List<int>>(e.TrackedUidsJson, JsonOptions) ?? [],
    };

    public static QuickPickAppliedStateEntity ToEntity(this QuickPickAppliedState m) => new()
    {
        UserId = m.UserId,
        ProfileNo = m.ProfileNo,
        QuickPickId = m.QuickPickId,
        AlarmType = m.AlarmType,
        AppliedAt = m.AppliedAt,
        ExcludePokemonIdsJson = JsonSerializer.Serialize(m.ExcludePokemonIds, JsonOptions),
        TrackedUidsJson = JsonSerializer.Serialize(m.TrackedUids, JsonOptions),
    };
}
